export const SHOW_USER_DETAILS_CARD = "SHOW_USER_DETAILS_CARD";
export const HIDE_USER_DETAILS_CARD = "HIDE_USER_DETAILS_CARD";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
